//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoutingServer.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IServiceProxy")]
    public interface IServiceProxy {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProxy/Get", ReplyAction="http://tempuri.org/IServiceProxy/GetResponse")]
        void Get(string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProxy/Get", ReplyAction="http://tempuri.org/IServiceProxy/GetResponse")]
        System.Threading.Tasks.Task GetAsync(string key);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceProxyChannel : RoutingServer.ServiceReference1.IServiceProxy, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceProxyClient : System.ServiceModel.ClientBase<RoutingServer.ServiceReference1.IServiceProxy>, RoutingServer.ServiceReference1.IServiceProxy {
        
        public ServiceProxyClient() {
        }
        
        public ServiceProxyClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceProxyClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceProxyClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceProxyClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Get(string key) {
            base.Channel.Get(key);
        }
        
        public System.Threading.Tasks.Task GetAsync(string key) {
            return base.Channel.GetAsync(key);
        }
    }
}
