//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEST.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IServiceRoutingServer")]
    public interface IServiceRoutingServer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRoutingServer/Add", ReplyAction="http://tempuri.org/IServiceRoutingServer/AddResponse")]
        int Add(int num1, int num2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRoutingServer/Add", ReplyAction="http://tempuri.org/IServiceRoutingServer/AddResponse")]
        System.Threading.Tasks.Task<int> AddAsync(int num1, int num2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRoutingServer/ComputeItineraire", ReplyAction="http://tempuri.org/IServiceRoutingServer/ComputeItineraireResponse")]
        string ComputeItineraire(string start, string end, string locomotion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRoutingServer/ComputeItineraire", ReplyAction="http://tempuri.org/IServiceRoutingServer/ComputeItineraireResponse")]
        System.Threading.Tasks.Task<string> ComputeItineraireAsync(string start, string end, string locomotion);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceRoutingServerChannel : TEST.ServiceReference1.IServiceRoutingServer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceRoutingServerClient : System.ServiceModel.ClientBase<TEST.ServiceReference1.IServiceRoutingServer>, TEST.ServiceReference1.IServiceRoutingServer {
        
        public ServiceRoutingServerClient() {
        }
        
        public ServiceRoutingServerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceRoutingServerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceRoutingServerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceRoutingServerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Add(int num1, int num2) {
            return base.Channel.Add(num1, num2);
        }
        
        public System.Threading.Tasks.Task<int> AddAsync(int num1, int num2) {
            return base.Channel.AddAsync(num1, num2);
        }
        
        public string ComputeItineraire(string start, string end, string locomotion) {
            return base.Channel.ComputeItineraire(start, end, locomotion);
        }
        
        public System.Threading.Tasks.Task<string> ComputeItineraireAsync(string start, string end, string locomotion) {
            return base.Channel.ComputeItineraireAsync(start, end, locomotion);
        }
    }
}
